name: Build Go Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Build
      run: go build -o myprogram.exe ./wpk.go
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: myprogram
        path: myprogram.exe
